import { FormEvent, useEffect, useRef, useState } from "react";
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate } from "react-router";
import { Icon } from "./components/icons";
import { ApiError, graphql, loginOperation, logoutOperation, registerOperation, setPasswordOperation, type Viewer, viewerOperation } from "./lib/graphql";

type AuthState = { viewer: Viewer | null | undefined; setViewer(viewer: Viewer | null): void };
const destination = (viewer: Viewer) => (viewer.onboardingCompleted ? "/profile" : "/onboarding");

function ProductIllustration() {
  const records = [["Experience", "Senior Product Engineer", "Shopify · Full-time"], ["Education", "Computer Science", "University of British Columbia"], ["Certification", "AWS Solutions Architect", "Amazon Web Services"]];
  return <section className="auth-art" aria-hidden="true"><div className="auth-showcase"><div className="auth-showcase-head"><div className="overline">Build a profile that stays useful</div><h2>Connect the parts of your professional story.</h2><p>Add structured experience and education, then keep the skills they support organized in one place.</p></div><div className="profile-illustration"><div className="illustration-grid"><div className="illustration-stack">{records.map(([kind, title, meta]) => <div className="illustration-card" key={kind}><div className="overline">{kind}</div><div className="title">{title}</div><div className="meta muted">{meta}</div></div>)}</div><div className="illustration-arrow">→</div><div className="illustration-card"><div className="overline">Your skills profile</div><div className="title">Skills connected to your profile</div><div className="illustration-skills">{["TypeScript", "System Design", "AWS", "Communication", "PostgreSQL"].map((skill) => <span className="chip" key={skill}>{skill}</span>)}</div><div className="meta muted" style={{ marginTop: 12 }}>Organize proficiency, add custom skills, and keep profile sources connected.</div></div></div></div><div className="auth-benefits">{["Catalog-backed suggestions with custom values when you need them.", "One Profile workspace for experience, education, certifications, and skills.", "Structured data that is easy to review and keep current."].map((benefit) => <div className="auth-benefit" key={benefit}><Icon name="check" /><span>{benefit}</span></div>)}</div></div></section>;
}

function AuthLayout({ children, showFooter = true }: { children: React.ReactNode; showFooter?: boolean }) { return <main className="public"><section className="auth-panel"><div className="auth-brand"><div className="logo">CP</div>Career Profile</div><div className="auth-card">{children}</div>{showFooter ? <div className="meta faint">Structured professional profiles, without the busywork.</div> : null}</section><ProductIllustration /></main>; }

function PasswordInput({ id, label, value, onChange, error, autoComplete, showLeadingIcon = false }: { id: string; label: string; value: string; onChange(value: string): void; error?: string; autoComplete: string; showLeadingIcon?: boolean }) {
  const [shown, setShown] = useState(false);
  return <div className="field"><label htmlFor={id}>{label}</label><div className="input-shell">{showLeadingIcon ? <span className="input-icon"><Icon name="lock" /></span> : null}<input className={`input with-trail${showLeadingIcon ? " with-icon" : ""}${error ? " error" : ""}`} id={id} type={shown ? "text" : "password"} value={value} autoComplete={autoComplete} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} onChange={(event) => onChange(event.target.value)} /><button className="trail buttonlike" type="button" aria-label={`${shown ? "Hide" : "Show"} ${label.toLowerCase()}`} aria-pressed={shown} onClick={() => setShown(!shown)}><Icon name="eye" /></button></div>{error ? <div className="help danger-text" id={`${id}-error`}>{error}</div> : null}</div>;
}
function ErrorSummary({ error, reference }: { error: string | null; reference: React.RefObject<HTMLDivElement | null> }) { return error ? <div ref={reference} className="callout danger" role="alert" tabIndex={-1}>{error}</div> : null; }
function EmailInput({ value, onChange, error, showLeadingIcon = false }: { value: string; onChange(value: string): void; error?: string; showLeadingIcon?: boolean }) { return <div className="field"><label htmlFor="email">Email</label><div className="input-shell">{showLeadingIcon ? <span className="input-icon"><Icon name="email" /></span> : null}<input className={`input${showLeadingIcon ? " with-icon" : ""}${error ? " error" : ""}`} id="email" type="email" placeholder="you@example.com" value={value} autoComplete="username" aria-invalid={Boolean(error)} aria-describedby={error ? "email-error" : undefined} onChange={(event) => onChange(event.target.value)} /></div>{error ? <div className="help danger-text" id="email-error">{error}</div> : null}</div>; }

function Register({ auth }: { auth: AuthState }) {
  const navigate = useNavigate(); const summary = useRef<HTMLDivElement>(null); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [errors, setErrors] = useState<Record<string, string>>({}); const [formError, setFormError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  useEffect(() => { if (formError) summary.current?.focus(); }, [formError]);
  async function submit(event: FormEvent) { event.preventDefault(); if (password !== confirm) { setErrors({ confirm: "Passwords do not match." }); return; } setPending(true); setFormError(null); try { const data = await graphql<{ register: { viewer: Viewer } }>(registerOperation, { input: { email, password } }); auth.setViewer(data.register.viewer); navigate(destination(data.register.viewer), { replace: true }); } catch (error) { const api = error as ApiError; setErrors(api.fieldErrors); setFormError(api.message); } finally { setPending(false); } }
  return <AuthLayout><div className="overline">Create account</div><h1>Start your Career Profile</h1><ErrorSummary error={formError} reference={summary} /><form className="stack" onSubmit={submit} noValidate><EmailInput value={email} onChange={setEmail} error={errors.email} /><PasswordInput id="register-password" label="Password" value={password} onChange={setPassword} error={errors.password} autoComplete="new-password" /><p className="help password-help">10+ chars, uppercase, lowercase, number, special character.</p><PasswordInput id="register-confirm" label="Verify password" value={confirm} onChange={setConfirm} error={errors.confirm} autoComplete="new-password" /><button className="btn primary lg" disabled={pending}>{pending ? "Creating account…" : "Create account"}</button></form><div className="meta muted auth-switch">Already have an account? <Link to="/login"><strong>Sign in</strong></Link></div></AuthLayout>;
}

function Login({ auth }: { auth: AuthState }) {
  const navigate = useNavigate(); const summary = useRef<HTMLDivElement>(null); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [formError, setFormError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  useEffect(() => { if (formError) summary.current?.focus(); }, [formError]);
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setFormError(null); try { const data = await graphql<{ login: { viewer: Viewer } }>(loginOperation, { input: { email, password } }); auth.setViewer(data.login.viewer); navigate(destination(data.login.viewer), { replace: true }); } catch (error) { setFormError((error as ApiError).message); } finally { setPending(false); } }
  return <AuthLayout><div className="overline">Welcome back</div><h1>Sign in to Career Profile</h1><p className="lead">Continue building your professional profile.</p><ErrorSummary error={formError} reference={summary} /><form className="stack" onSubmit={submit}><EmailInput value={email} onChange={setEmail} showLeadingIcon /><PasswordInput id="login-password" label="Password" value={password} onChange={setPassword} autoComplete="current-password" showLeadingIcon /><button className="btn primary lg" disabled={pending}>{pending ? "Signing in…" : "Sign in"}</button></form><div className="meta muted auth-switch">New here? <Link to="/register"><strong>Create an account</strong></Link></div></AuthLayout>;
}

function SetPassword({ auth }: { auth: AuthState }) {
  const navigate = useNavigate(); const [proof] = useState(() => new URLSearchParams(window.location.hash.slice(1)).get("proof") ?? ""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState<string | null>(proof ? null : "This setup link is invalid, expired, or already used."); const [pending, setPending] = useState(false);
  useEffect(() => { if (window.location.hash) window.history.replaceState(null, "", `${window.location.pathname}${window.location.search}`); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); if (password !== confirm) { setError("Passwords do not match."); return; } setPending(true); setError(null); try { const data = await graphql<{ setPassword: { viewer: Viewer } }>(setPasswordOperation, { input: { proof, password } }); auth.setViewer(data.setPassword.viewer); navigate(destination(data.setPassword.viewer), { replace: true }); } catch (exception) { setError((exception as ApiError).message); } finally { setPending(false); } }
  return <AuthLayout showFooter={false}><div className="overline">Account setup</div><h1>Set your password</h1><p className="lead">Your account is ready. Create a strong password before continuing to your profile setup.</p>{error ? <div className="callout danger" role="alert">{error}</div> : null}{proof ? <form className="stack" onSubmit={submit}><PasswordInput id="setup-password" label="Password" value={password} onChange={setPassword} autoComplete="new-password" /><p className="help password-help">10+ chars, uppercase, lowercase, number, special character.</p><PasswordInput id="setup-confirm" label="Verify password" value={confirm} onChange={setConfirm} autoComplete="new-password" /><button className="btn primary lg" disabled={pending}>{pending ? "Saving password…" : "Set password & continue"}</button></form> : null}</AuthLayout>;
}
function Destination({ auth, required }: { auth: AuthState; required: "complete" | "incomplete" }) { if (!auth.viewer) return <Navigate to="/login" replace />; if ((required === "complete") !== auth.viewer.onboardingCompleted) return <Navigate to={destination(auth.viewer)} replace />; return <main className="destination"><h1>{required === "complete" ? "Profile" : "Onboarding"}</h1><p>This protected destination will be completed in Phase 02.</p><button onClick={async () => { await graphql(logoutOperation); auth.setViewer(null); }}>Sign out</button></main>; }
function RouterApp() { const [viewer, setViewer] = useState<Viewer | null | undefined>(undefined); useEffect(() => { void graphql<{ viewer: Viewer | null }>(viewerOperation).then((data) => setViewer(data.viewer)).catch(() => setViewer(null)); }, []); const auth: AuthState = { viewer, setViewer }; if (viewer === undefined) return <main className="loading" aria-live="polite">Loading Career Profile…</main>; const redirect = viewer ? destination(viewer) : undefined; return <Routes><Route path="/login" element={redirect ? <Navigate to={redirect} replace /> : <Login auth={auth} />} /><Route path="/register" element={redirect ? <Navigate to={redirect} replace /> : <Register auth={auth} />} /><Route path="/set-password" element={<SetPassword auth={auth} />} /><Route path="/profile" element={<Destination auth={auth} required="complete" />} /><Route path="/onboarding" element={<Destination auth={auth} required="incomplete" />} /><Route path="*" element={<Navigate to={redirect ?? "/login"} replace />} /></Routes>; }
export default function App() { return <BrowserRouter><RouterApp /></BrowserRouter>; }
