import { FormEvent, useEffect, useRef, useState } from "react";
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate } from "react-router";
import { ApiError, graphql, loginOperation, logoutOperation, registerOperation, setPasswordOperation, type Viewer, viewerOperation } from "./lib/graphql";

type AuthState = { viewer: Viewer | null | undefined; setViewer(viewer: Viewer | null): void };
const destination = (viewer: Viewer) => (viewer.onboardingCompleted ? "/profile" : "/onboarding");

function Illustration() { return <aside className="auth-illustration" aria-hidden="true"><p>Build your professional story</p>{["Experience", "Education", "Certification"].map((label) => <div className="story-card" key={label}><span>{label}</span><i /><span>Skills profile</span></div>)}</aside>; }
function PasswordInput({ id, label, value, onChange, error, autoComplete }: { id: string; label: string; value: string; onChange(value: string): void; error?: string; autoComplete: string }) { const [shown, setShown] = useState(false); return <div className="field"><label htmlFor={id}>{label}</label><span className="password-wrap"><input id={id} type={shown ? "text" : "password"} value={value} autoComplete={autoComplete} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} onChange={(event) => onChange(event.target.value)} /><button type="button" className="eye" aria-label={`${shown ? "Hide" : "Show"} ${label.toLowerCase()}`} aria-pressed={shown} onClick={() => setShown(!shown)}>{shown ? "Hide" : "Show"}</button></span>{error ? <small id={`${id}-error`}>{error}</small> : null}</div>; }
function AuthLayout({ children }: { children: React.ReactNode }) { return <main className="auth-page"><section className="auth-panel">{children}</section><Illustration /></main>; }
function ErrorSummary({ error, reference }: { error: string | null; reference: React.RefObject<HTMLDivElement | null> }) { return error ? <div ref={reference} className="form-error" role="alert" tabIndex={-1}>{error}</div> : null; }

function Register({ auth }: { auth: AuthState }) {
  const navigate = useNavigate(); const summary = useRef<HTMLDivElement>(null); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [errors, setErrors] = useState<Record<string, string>>({}); const [formError, setFormError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  useEffect(() => { if (formError) summary.current?.focus(); }, [formError]);
  async function submit(event: FormEvent) { event.preventDefault(); if (password !== confirm) { setErrors({ confirm: "Passwords must match." }); return; } setPending(true); setFormError(null); try { const data = await graphql<{ register: { viewer: Viewer } }>(registerOperation, { input: { email, password } }); auth.setViewer(data.register.viewer); navigate(destination(data.register.viewer), { replace: true }); } catch (error) { const api = error as ApiError; setErrors(api.fieldErrors); setFormError(api.message); } finally { setPending(false); } }
  return <AuthLayout><p className="eyebrow">Career Profile</p><h1>Create your account</h1><ErrorSummary error={formError} reference={summary} /><form onSubmit={submit} noValidate><label className="field">Email<input type="email" value={email} autoComplete="username" aria-invalid={Boolean(errors.email)} onChange={(event) => setEmail(event.target.value)} />{errors.email ? <small>{errors.email}</small> : null}</label><PasswordInput id="register-password" label="Password" value={password} onChange={setPassword} error={errors.password} autoComplete="new-password" /><PasswordInput id="register-confirm" label="Verify password" value={confirm} onChange={setConfirm} error={errors.confirm} autoComplete="new-password" /><p className="hint">10+ characters with uppercase, lowercase, number, and symbol.</p><button className="primary" disabled={pending}>{pending ? "Creating account…" : "Create account"}</button></form><p className="switch">Already have an account? <Link to="/login">Sign in</Link></p></AuthLayout>;
}

function Login({ auth }: { auth: AuthState }) {
  const navigate = useNavigate(); const summary = useRef<HTMLDivElement>(null); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [formError, setFormError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  useEffect(() => { if (formError) summary.current?.focus(); }, [formError]);
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setFormError(null); try { const data = await graphql<{ login: { viewer: Viewer } }>(loginOperation, { input: { email, password } }); auth.setViewer(data.login.viewer); navigate(destination(data.login.viewer), { replace: true }); } catch (error) { setFormError((error as ApiError).message); } finally { setPending(false); } }
  return <AuthLayout><p className="eyebrow">Career Profile</p><h1>Welcome back</h1><ErrorSummary error={formError} reference={summary} /><form onSubmit={submit}><label className="field">Email<input type="email" value={email} autoComplete="username" onChange={(event) => setEmail(event.target.value)} /></label><PasswordInput id="login-password" label="Password" value={password} onChange={setPassword} autoComplete="current-password" /><button className="primary" disabled={pending}>{pending ? "Signing in…" : "Sign in"}</button></form><p className="switch">New here? <Link to="/register">Create an account</Link></p></AuthLayout>;
}

function SetPassword({ auth }: { auth: AuthState }) {
  const navigate = useNavigate(); const [proof] = useState(() => new URLSearchParams(window.location.hash.slice(1)).get("proof") ?? ""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState<string | null>(proof ? null : "This setup link is invalid, expired, or already used."); const [pending, setPending] = useState(false);
  useEffect(() => { if (window.location.hash) window.history.replaceState(null, "", `${window.location.pathname}${window.location.search}`); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); if (password !== confirm) { setError("Passwords must match."); return; } setPending(true); setError(null); try { const data = await graphql<{ setPassword: { viewer: Viewer } }>(setPasswordOperation, { input: { proof, password } }); auth.setViewer(data.setPassword.viewer); navigate(destination(data.setPassword.viewer), { replace: true }); } catch (exception) { setError((exception as ApiError).message); } finally { setPending(false); } }
  return <AuthLayout><p className="eyebrow">Career Profile</p><h1>Set your password</h1><p className="hint">Choose a password to continue to your profile.</p>{error ? <div className="form-error" role="alert">{error}</div> : null}{proof ? <form onSubmit={submit}><PasswordInput id="setup-password" label="Password" value={password} onChange={setPassword} autoComplete="new-password" /><PasswordInput id="setup-confirm" label="Verify password" value={confirm} onChange={setConfirm} autoComplete="new-password" /><button className="primary" disabled={pending}>{pending ? "Saving password…" : "Set password & continue"}</button></form> : null}</AuthLayout>;
}

function Destination({ auth, required }: { auth: AuthState; required: "complete" | "incomplete" }) { if (!auth.viewer) return <Navigate to="/login" replace />; if ((required === "complete") !== auth.viewer.onboardingCompleted) return <Navigate to={destination(auth.viewer)} replace />; return <main className="destination"><h1>{required === "complete" ? "Profile" : "Onboarding"}</h1><p>This protected destination will be completed in Phase 02.</p><button onClick={async () => { await graphql(logoutOperation); auth.setViewer(null); }}>Sign out</button></main>; }
function RouterApp() { const [viewer, setViewer] = useState<Viewer | null | undefined>(undefined); useEffect(() => { void graphql<{ viewer: Viewer | null }>(viewerOperation).then((data) => setViewer(data.viewer)).catch(() => setViewer(null)); }, []); const auth: AuthState = { viewer, setViewer }; if (viewer === undefined) return <main className="loading" aria-live="polite">Loading Career Profile…</main>; const redirect = viewer ? destination(viewer) : undefined; return <Routes><Route path="/login" element={redirect ? <Navigate to={redirect} replace /> : <Login auth={auth} />} /><Route path="/register" element={redirect ? <Navigate to={redirect} replace /> : <Register auth={auth} />} /><Route path="/set-password" element={<SetPassword auth={auth} />} /><Route path="/profile" element={<Destination auth={auth} required="complete" />} /><Route path="/onboarding" element={<Destination auth={auth} required="incomplete" />} /><Route path="*" element={<Navigate to={redirect ?? "/login"} replace />} /></Routes>; }
export default function App() { return <BrowserRouter><RouterApp /></BrowserRouter>; }
